import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Web Authn Test</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>Web Authn Test</h1>
      </main>

      <footer>
        <a href="https://github.com/BlueZeeKing">BlueZeeKing</a>
      </footer>
    </div>
  )
}
